# Copyright 2018, IBM.
#
# This source code is licensed under the Apache License, Version 2.0 found in
# the LICENSE.txt file in the root directory of this source tree.

notifications:
  email: false

cache: pip
sudo: false

###############################################################################
# Anchored and aliased definitions.
###############################################################################

# These are used for avoiding repeating code, and due to problems with
# overriding some keys (in particular, "os" and "language: ptyhon") when using
# the standard travis matrix with stages.
#
# This allows re-using different "sets" of configurations in the stages
# matrix, mimicking a hierarchy:
# * stage_generic
#   * stage_linux
#   * stage_osx

stage_generic: &stage_generic
  install:
    # Install step for jobs that require compilation and qa.
    - pip install -U -r requirements.txt
    - pip install -U -r requirements-dev.txt
  script:
    # Run the tests
    - make test

stage_linux: &stage_linux
  <<: *stage_generic
  os: linux
  dist: trusty
  language: python
  python: 3.5
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - cmake
        - liblapack-dev
        - libblas-dev
        - g++-5

stage_osx: &stage_osx
  <<: *stage_generic
  os: osx
  osx_image: xcode9.2
  language: generic
  before_install:
    # Travis does not provide support for Python 3 under osx - it needs to be
    # installed manually.
    |
    if [ ${TRAVIS_OS_NAME} = "osx" ]; then
      brew upgrade pyenv || brew install pyenv
      pyenv install 3.6.5
      ~/.pyenv/versions/3.6.5/bin/python -m venv venv
      source venv/bin/activate
    fi


###############################################################################
# Stage-related definitions
###############################################################################

# Define the order of the stages.
stages:
  - lint
  - test

# Define the job matrix explicitly, as matrix expansion causes issues when
# using it with stages and some variables/sections cannot be overridden.
jobs:
  include:
    # "lint and and pure python test" stage
    ###########################################################################
    # Linter and style check (GNU/Linux, Python 3.5)
    - stage: lint
      <<: *stage_linux
      script: make style && make lint

    # "test" stage
    ###########################################################################
    # GNU/Linux, Python 3.5
    - stage: test
      <<: *stage_linux

    # GNU/Linux, Python 3.6
    - stage: test
      <<: *stage_linux
      python: 3.6

    # OSX, Python 3.latest (brew does not support versioning)
    - stage: test
      <<: *stage_osx
